## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [123]:
print("Get the outer product WITHOUT using numpy\n")
# import library
import numpy as np

# create 2 vectors with ranges [5,10] and [15,20]
vectorDragon = np.arange(5,10)
vectorWizard = np.arange(15,20)

print("Vector with range [5,10]:\n",vectorDragon)
print("\nVector with range [15,20]:\n",vectorWizard)

# create empty list to contain outer product
outerProduct = []

# boolean expression: if condition returns true, keep going
# if not, print error code
assert (len(vectorDragon)==len(vectorWizard)), "Lists aren't the same length"

for i in range(len(vectorDragon)):
    row = []
    for j in range(len(vectorWizard)):
        row.append(vectorDragon[i]*vectorWizard[j])
    outerProduct.append(row)

print("\nOuter product of the above vectors:") 
outerProduct

Get the outer product WITHOUT using numpy

Vector with range [5,10]:
 [5 6 7 8 9]

Vector with range [15,20]:
 [15 16 17 18 19]

Outer product of the above vectors:


[[75, 80, 85, 90, 95],
 [90, 96, 102, 108, 114],
 [105, 112, 119, 126, 133],
 [120, 128, 136, 144, 152],
 [135, 144, 153, 162, 171]]

In [184]:
print("Get the trace WITHOUT using numpy\n")

# from first row, take 0th element
# from second row, add 0 + 0+1 element

trace = 0

for i in range(len(outerProduct)):
    trace += (M[i][i])
    
print("\nTrace:",trace)

Get the trace WITHOUT using numpy


Trace: 605


In [33]:
print("Get the outer product using numpy\n")

outerProductNP = np.outer(vectorDragon,vectorWizard)
outerProductNP

Get the outer product using numpy



array([[ 75,  80,  85,  90,  95],
       [ 90,  96, 102, 108, 114],
       [105, 112, 119, 126, 133],
       [120, 128, 136, 144, 152],
       [135, 144, 153, 162, 171]])

In [183]:
print("Get the trace using numpy\n")
traceNP = np.trace(outerProductNP)
print("Trace:",traceNP)

Get the trace using numpy

Trace: 605


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    

2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [229]:
# When they say "inner dimensions match," they mean the two values
# on the inside literally. i.e. 2x3 * 3x5 --> the threes match

# rows x columns -->
# we're multiplying the ROWS of matrix A by the COLUMNS of matrix B
# and then summing those values from one combined row and column

matrixShark = np.random.rand(4,3)
matrixFish = np.random.rand(3,4)

print("Matrix A\n",matrixShark)
print("\nMatrix B\n",matrixFish)

print("\nMethod 1 - For loop\n")

print(range(len(matrixShark)))

x = [0]

for i in range(len(matrixFish)):
    for i in range(len(matrixShark)):
        x.append(matrixFish[0][i] * matrixShark[i][0])

print(sum(x[0:4]))

print("\nMethod 2 - List comprehension\n")



print("\nMethod 3 - Numpy operator\n")

print(np.dot(matrixShark,matrixFish))

Matrix A
 [[0.29362859 0.36391101 0.9991638 ]
 [0.05221461 0.04154579 0.90238996]
 [0.1526486  0.88882647 0.08633755]
 [0.69976527 0.91181885 0.92449441]]

Matrix B
 [[0.93170519 0.64974679 0.39057242 0.9867212 ]
 [0.73697589 0.44627179 0.76022595 0.60615017]
 [0.95207163 0.28204169 0.47584255 0.2247583 ]]

Method 1 - For loop

range(0, 4)
0.36712188525755274

Method 2 - List comprehension


Method 3 - Numpy operator

[[1.49304442 0.6349933  0.86678247 0.73488463]
 [0.93840674 0.30697858 0.48137331 0.27952387]
 [0.87946671 0.52019191 0.77641237 0.70878901]
 [2.20414833 1.12233523 1.40641114 1.45096016]]
